# Generated by Django 4.2.2 on 2025-10-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0002_destino_entrada"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Destino",
        ),
        migrations.DeleteModel(
            name="Entrada",
        ),
    ]
