# Generated by Django 4.2.2 on 2025-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0004_timelineevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelineevent",
            old_name="data_evento",
            new_name="data",
        ),
    ]
