# Generated by Django 4.2.2 on 2025-10-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0006_evento_confirmado_evento_familia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="familia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to="seapac.family",
            ),
        ),
    ]
