# Generated by Django 4.2.2 on 2025-10-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0007_alter_evento_familia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
