# Generated by Django 4.2.2 on 2025-10-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0008_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsystem",
            name="descricao",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
