# Generated by Django 4.2.2 on 2025-10-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0009_subsystem_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsystem",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="subsistemas/",
                verbose_name="Foto do Subsistema",
            ),
        ),
    ]
