# Generated by Django 4.2.2 on 2025-10-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0010_subsystem_foto_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsystem",
            old_name="foto_perfil",
            new_name="foto_subsistema",
        ),
    ]
