# Generated by Django 4.2.2 on 2025-10-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0012_subsystem_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsystem",
            name="tipo",
            field=models.CharField(
                choices=[("TS", "Tecnologia Social"), ("SS", "Subsistema")],
                default="SS",
                max_length=2,
            ),
        ),
    ]
