# Generated by Django 4.2.2 on 2025-10-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0013_alter_subsystem_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="terra",
        ),
        migrations.AddField(
            model_name="family",
            name="municipio",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="seapac.municipality",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Terrain",
        ),
    ]
