# Generated by Django 4.2.2 on 2025-10-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0015_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="renda",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="nome_projeto",
            field=models.CharField(max_length=200),
        ),
    ]
