# Generated by Django 4.2.2 on 2025-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0019_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="especialidade",
            field=models.CharField(
                choices=[
                    ("agropecuária", "Agropecuária"),
                    ("veterinário", "Veterinário"),
                    ("agronomia", "Agronomia"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="nome_tecnico",
            field=models.CharField(max_length=50),
        ),
    ]
