# Generated by Django 4.2.2 on 2025-11-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0020_technician_especialidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="descricao",
        ),
    ]
