# Generated by Django 4.2.2 on 2025-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0022_evento_data_alter_evento_inicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="inicio",
        ),
        migrations.AlterField(
            model_name="evento",
            name="data",
            field=models.DateField(),
        ),
    ]
