version: '3.8'

services:

  postgres:
    image: postgres:latest
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: seapac
    command: ./start
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    env_file: ".env"
    depends_on:
      - postgres
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    environment:
      VIRTUAL_HOST: seapac.nadic.ifrn.edu.br
      VIRTUAL_POST: 80
      LETSENCRYPT_HOST: seapac.nadic.ifrn.edu.br
    networks:
      - web-proxy
      - default
    restart: unless-stopped
  
volumes:
  pgdata:
  media_data:
  static_data:

networks:
  web-proxy:
   external: true
  
