# Generated by Django 5.2.5 on 2025-10-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
