# Generated by Django 4.2.2 on 2025-10-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seapac", "0006_evento_confirmado_evento_familia"),
        ("usuarios", "0002_alter_usuario_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="nome_cidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapac.municipality",
            ),
        ),
    ]
