# Generated by Django 4.2.2 on 2025-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_nome_cidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=18, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
